// <auto-generated />
namespace ThuVien.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateID_GV_MH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateID_GV_MH));
        
        string IMigrationMetadata.Id
        {
            get { return "201705031236448_updateID_GV_MH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
